server:
  port: 8080

spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

mybatis:
  mapper-locations: classpath*:mapper/*.xml
